name: Customers API CI on ECR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build, tag, and push to ECR
        id: build-image
        env:
          IMAGE_TAG: 0.0.1
        run: |
          docker build -f src/Customers.Api/Dockerfile .